"""
Django settings for portfolio_core project.

Generated by Django 5.2.4 on 2026-01-12
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'debug_toolbar',

    # Приложения
    'apps.main',
    'apps.portfolio',
    'apps.solutions',
    'apps.custom_admin',
    'apps.api',
]

# Переопределяем модель пользователя
AUTH_USER_MODEL = 'main.AdminUser'  # Указываем кастомную модель пользователя

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.gzip.GZipMiddleware',
]

# HTML минификация
HTML_MINIFY = True

# Предзагрузка ресурсов
PRELOAD_RESOURCES = [
    ('style', '/static/css/global.css'),
    ('script', '/static/js/global.js'),
    ('font', 'https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Inter:wght@400;500&display=swap'),
]

ROOT_URLCONF = 'portfolio_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Глобальные шаблоны проекта
        ],
        'APP_DIRS': True,  # Разрешаем поиск шаблонов в папках приложений
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'solutions.context_processors.cart_context',
                # Кастомные контекстные процессоры
                'apps.main.context_processors.site_settings',
            ],
            'builtins': [
                # Добавляем кастомные теги шаблонов
                'apps.main.templatetags.main_extras',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Alternatively, use DATABASE_URL from .env
if env('DATABASE_URL', default=None):
    DATABASES = {
        'default': env.db('DATABASE_URL')
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'ru-ru'  # Изменили на русский для сайта
TIME_ZONE = 'Europe/Moscow'  # Московское время
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Основные статические файлы проекта
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Директории со статическими файлами
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Глобальная статика проекта
    os.path.join(BASE_DIR, 'apps/main/static'),  # Статика главного приложения
    os.path.join(BASE_DIR, 'apps/portfolio/static'),  # Статика портфолио
    os.path.join(BASE_DIR, 'apps/solutions/static'),  # Статика решений
]

# Хранилище для статики в production
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Cache control для статических файлов (оптимизация)
STATICFILES_CACHE_CONTROL = {
    '*.css': 'public, max-age=31536000, immutable',
    '*.js': 'public, max-age=31536000, immutable',
    '*.svg': 'public, max-age=31536000, immutable',
    '*.png': 'public, max-age=31536000, immutable',
    '*.jpg': 'public, max-age=31536000, immutable',
    '*.webp': 'public, max-age=31536000, immutable',
    '*.woff': 'public, max-age=31536000, immutable',
    '*.woff2': 'public, max-age=31536000, immutable',
    '*.ttf': 'public, max-age=31536000, immutable',
}

# Media files (загружаемые пользователями)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Папка для загрузок
UPLOAD_FOLDER = os.path.join(BASE_DIR, 'uploads')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'svg', 'webp', 'pdf', 'doc', 'docx'}

# Создаем директории при необходимости
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(STATIC_ROOT, exist_ok=True)

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Email settings (from Flask config)
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.mail.ru')
EMAIL_PORT = env.int('EMAIL_PORT', default=465)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='ganef85@mail.ru')
EMAIL_HOST_PASSWORD = env('MAIL_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='ganef85@mail.ru')
EMAIL_TIMEOUT = 30

# Настройки сессий
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 недели
SESSION_COOKIE_NAME = 'portfolio_session'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # Только HTTPS в production
CSRF_COOKIE_SECURE = not DEBUG  # Только HTTPS в production

# Логирование
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.main': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Настройки приложения
SITE_NAME = "Портфолио разработчика"
SITE_DESCRIPTION = "Создание сайтов для бизнеса за 2 недели"
SITE_URL = env('SITE_URL', default='http://localhost:8000')

# Настройки для приложения main
MAIN_APP_CONFIG = {
    'HERO_TITLE': 'Ваш готовый сайт за 2 недели!',
    'HERO_TEXT': 'Создаю современные сайты и MVP для бизнеса — быстро, качественно, с фиксированной стоимостью',
    'CONTACT_PHONE': '+7 (999) 123-45-67',
    'CONTACT_EMAIL': 'info@example.com',
    'CONTACT_CITY': 'Санкт-Петербург',
}

# Конфигурация для Django Debug Toolbar
if DEBUG:
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: True,
    }
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Дополнительные настройки безопасности
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'

    # Настройки для WhiteNoise (статики)
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'